name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main   # main ব্রাঞ্চে push হলে রান হবে

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        run: |
          echo "Purging jsDelivr cache..."
          curl -s "https://purge.jsdelivr.net/gh/kajalmondal661/bangla-calendar-config@main/config.json"
          curl -s "https://purge.jsdelivr.net/gh/kajalmondal661/bangla-calendar-config@main/*"
