name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache for config.json
        run: |
          echo "Purging jsDelivr cache..."
          curl -i "https://purge.jsdelivr.net/gh/kajalmondal661/bangla-calendar-config@main/config.json"
